sudo: require
services:
  - docker
script:
  - docker build ./client -t awnali/multi-container-complex-client
  - docker build ./server -t awnali/multi-container-complex-server
  - docker build ./worker -t awnali/multi-container-complex-worker
  - docker build ./ngnix -t awnali/multi-container-complex-ngnix
