version: "3"
services:
  web-server:
    build: ./nginx
    ports:
      - "3200:8084"
    restart: on-failure
    depends_on:
      - client
  redis:
    image: "redis"
  client:
    build: ./client
    restart: on-failure
    depends_on:
      - api
  api:
    build: ./server
    depends_on:
      - worker
    environment:
      - REDIS_HOST=redis
  worker:
    build: ./worker
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
