version: "3"
services:
  web-server:
    build: ./nginx
    ports:
      - "3200:8084"
    restart: on-failure
    depends_on:
      - client
  redis:
    image: "redis"
    ports:
      - "6379:6379"
  client:
    build: ./client
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      - api
  api:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - worker
    environment:
      - REDIS_HOST=redis
  worker:
    build: ./worker
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
